### ISSUE TITLE
what is difference between rev3 and rev 4 . By the way , thankyou for such an awesome stuff! :)

### ISSUE THREAD

**Issue by shubhmak** [uStepper/Robot-Arm-Rev-4#2]
i was just windering what is the difference between rev3 and rev 4 of the arm..... just curious (and a bit lazy too lol).

**Comment by uStepperOld** [comment]
Hi,
The gears have been switched to belt drives from 3 to 4, more stability has been added by using thrust bearings and a lot of work went into optimizing the design to minimize unique parts in the design. Almost all the plastic parts were redesigned but based on the old look.

Best regards,
Mogens
